# Generated by Django 6.0.2 on 2026-02-22 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35ab98f5-70d5-40e0-a9b3-bd2691f2e791'), editable=False, primary_key=True, serialize=False),
        ),
    ]
