# Generated by Django 6.0.2 on 2026-02-22 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('222fccb4-4609-4932-a2e8-5b6125348574'), editable=False, primary_key=True, serialize=False),
        ),
    ]
