# Generated by Django 6.0.2 on 2026-02-22 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7030feb4-db9a-46bb-8df2-1225e6f22b94'), editable=False, primary_key=True, serialize=False),
        ),
    ]
