# Generated by Django 6.0.2 on 2026-02-22 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ai_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba25207b-fa37-462d-8940-359196a08357'), editable=False, primary_key=True, serialize=False),
        ),
    ]
