# Generated by Django 6.0.2 on 2026-02-22 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultation_ai_summary_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6cb650a1-99ca-434e-9f16-ff203a4b2699'), editable=False, primary_key=True, serialize=False),
        ),
    ]
