# Generated by Django 6.0.2 on 2026-02-22 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
