# Generated by Django 6.0.2 on 2026-02-22 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7f23cd5-ac12-4742-90ca-0157ac64a32c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
