# Generated by Django 6.0.2 on 2026-02-22 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14cb5d2e-47e9-4863-92da-f784a913ea8c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
