# Generated by Django 6.0.2 on 2026-02-22 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5c1ac4c-8c3b-4182-8670-61cb3b4be8da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
