# Generated by Django 6.0.2 on 2026-02-22 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d2f892-91a6-493e-8ca1-97c6e37abebc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
