# Generated by Django 6.0.2 on 2026-02-22 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7609c73-c599-4d80-a55e-d9d6027fd951'), editable=False, primary_key=True, serialize=False),
        ),
    ]
