# Generated by Django 6.0.2 on 2026-02-22 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60594419-fc33-4597-85a9-719e3f396d9f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
